# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b6f9a32229e43fa1974a598ca103ad4f46d91a0182edf84b5b2506f933136159c8bed6eb14c87da0414177f55887ef54559d6778ae1aab45e3813e6cd7eb847

test:
  secret_key_base: c43f5cbffdc6c4d0b25958ba11dbff6a7d02e334bb322900cb86576da72e83f03ba682a159a5040bbb1270082befc7130b47645d96c0aedae9f693cb9a8b3821

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
